// Generated by gencpp from file docking/DockRequest.msg
// DO NOT EDIT!


#ifndef DOCKING_MESSAGE_DOCKREQUEST_H
#define DOCKING_MESSAGE_DOCKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace docking
{
template <class ContainerAllocator>
struct DockRequest_
{
  typedef DockRequest_<ContainerAllocator> Type;

  DockRequest_()
    : fiducial_id(0)
    , waypoints()  {
    }
  DockRequest_(const ContainerAllocator& _alloc)
    : fiducial_id(0)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _fiducial_id_type;
  _fiducial_id_type fiducial_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::docking::DockRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::docking::DockRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DockRequest_

typedef ::docking::DockRequest_<std::allocator<void> > DockRequest;

typedef boost::shared_ptr< ::docking::DockRequest > DockRequestPtr;
typedef boost::shared_ptr< ::docking::DockRequest const> DockRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::docking::DockRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::docking::DockRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace docking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::docking::DockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::docking::DockRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::docking::DockRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::docking::DockRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::docking::DockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::docking::DockRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::docking::DockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "826f5b01681469068c9a8613e832ec93";
  }

  static const char* value(const ::docking::DockRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x826f5b0168146906ULL;
  static const uint64_t static_value2 = 0x8c9a8613e832ec93ULL;
};

template<class ContainerAllocator>
struct DataType< ::docking::DockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "docking/DockRequest";
  }

  static const char* value(const ::docking::DockRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::docking::DockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 fiducial_id\n\
string waypoints\n\
";
  }

  static const char* value(const ::docking::DockRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::docking::DockRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fiducial_id);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::docking::DockRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::docking::DockRequest_<ContainerAllocator>& v)
  {
    s << indent << "fiducial_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fiducial_id);
    s << indent << "waypoints: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.waypoints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOCKING_MESSAGE_DOCKREQUEST_H
