// Generated by gencpp from file docking/Dock.msg
// DO NOT EDIT!


#ifndef DOCKING_MESSAGE_DOCK_H
#define DOCKING_MESSAGE_DOCK_H

#include <ros/service_traits.h>


#include <docking/DockRequest.h>
#include <docking/DockResponse.h>


namespace docking
{

struct Dock
{

typedef DockRequest Request;
typedef DockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Dock
} // namespace docking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::docking::Dock > {
  static const char* value()
  {
    return "112bdf241f064beb58699184e7082608";
  }

  static const char* value(const ::docking::Dock&) { return value(); }
};

template<>
struct DataType< ::docking::Dock > {
  static const char* value()
  {
    return "docking/Dock";
  }

  static const char* value(const ::docking::Dock&) { return value(); }
};


// service_traits::MD5Sum< ::docking::DockRequest> should match 
// service_traits::MD5Sum< ::docking::Dock > 
template<>
struct MD5Sum< ::docking::DockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::docking::Dock >::value();
  }
  static const char* value(const ::docking::DockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::docking::DockRequest> should match 
// service_traits::DataType< ::docking::Dock > 
template<>
struct DataType< ::docking::DockRequest>
{
  static const char* value()
  {
    return DataType< ::docking::Dock >::value();
  }
  static const char* value(const ::docking::DockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::docking::DockResponse> should match 
// service_traits::MD5Sum< ::docking::Dock > 
template<>
struct MD5Sum< ::docking::DockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::docking::Dock >::value();
  }
  static const char* value(const ::docking::DockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::docking::DockResponse> should match 
// service_traits::DataType< ::docking::Dock > 
template<>
struct DataType< ::docking::DockResponse>
{
  static const char* value()
  {
    return DataType< ::docking::Dock >::value();
  }
  static const char* value(const ::docking::DockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOCKING_MESSAGE_DOCK_H
